### ISSUE TITLE
Callback on construct will not call when connected.

### ISSUE THREAD

**Issue by xpader** [walkor/redis#2]
https://github.com/walkor/redis/blob/922218dffddf08354e0269202ac21d2d34332850/src/Client.php#L345

_firstConnect was set to false when try to call _connectionCallback.

https://github.com/walkor/redis/blob/922218dffddf08354e0269202ac21d2d34332850/src/Client.php#L351

**Comment by walkor** [comment]
Fixed. Please upgrade workerman/redis.
