### ISSUE TITLE
get获取不到值

### ISSUE THREAD

**Issue by lozhu** [walkor/redis#9]
get获取的值一直是NULL,set可以成功，数据库里有值

**Comment by walkor** [comment]
发下测试代码

**Comment by lozhu** [comment]
框架：gatewayworker 3.0 
组件：workman/redis 
测试代码：
$redis->set('games', json_encode([1, 2]));
var_dump($redis->get('games'));
最后值一直是NULL,换成原生phpredis，此段代码正常获取到值

**Comment by lozhu** [comment]
是因为使用gatewayworker框架的原因吗？这个框架说workman能用的组件，这个框架应该都能用的。

**Comment by lozhu** [comment]
如果换成 $redis->hMSet()和$redis->hMGet()方法可以正常获取和设置值。用get方法获取不到值，set方法可以设置值

**Comment by walkor** [comment]
这个是异步库，不支持同步用法，文档也有详细用法。
如果对异步不熟悉，建议直接用redis扩展。
